create or replace TABLE NYC_TAXI_DB.ANALYTICS.NYC_GOLD_BUSINESS_STATS (
	TOTAL_TRIPS NUMBER(38,0),
	TOTAL_DAYS NUMBER(38,0),
	TOTAL_REVENUE FLOAT,
	AVG_REVENUE_PER_TRIP FLOAT,
	TOTAL_MILES FLOAT,
	AVG_TRIP_DISTANCE FLOAT,
	AVG_PASSENGERS FLOAT,
	AVG_TIP_PERCENTAGE FLOAT,
	AVG_DAILY_TRIPS FLOAT,
	AVG_DAILY_REVENUE FLOAT,
	REVENUE_PER_MILE FLOAT,
	PROCESSING_TIMESTAMP TIMESTAMP_NTZ(9),
	REPORT_PERIOD_START DATE,
	REPORT_PERIOD_END DATE
);