create or replace TABLE NYC_TAXI_DB.ANALYTICS.NYC_GOLD_PAYMENT_STATS (
	PAYMENT_TYPE NUMBER(38,0) NOT NULL,
	IS_WEEKEND BOOLEAN NOT NULL,
	TOTAL_TRIPS NUMBER(38,0),
	AVG_FARE FLOAT,
	AVG_TIP FLOAT,
	AVG_TIP_PERCENTAGE FLOAT,
	TOTAL_REVENUE FLOAT,
	MEDIAN_TIP_PERCENTAGE FLOAT,
	PAYMENT_METHOD VARCHAR(16777216),
	DAY_TYPE VARCHAR(16777216),
	PROCESSING_TIMESTAMP TIMESTAMP_NTZ(9),
	constraint PK_PAYMENT_STATS primary key (PAYMENT_TYPE, IS_WEEKEND)
);