create or replace TABLE NYC_TAXI_DB.STAGE.NYC_GOLD_LOCATION_STATS (
	PULOCATIONID NUMBER(38,0),
	TOTAL_PICKUPS NUMBER(38,0),
	AVG_TRIP_DISTANCE FLOAT,
	AVG_FARE FLOAT,
	TOTAL_REVENUE FLOAT,
	DOLOCATIONID NUMBER(38,0),
	TOTAL_DROPOFFS NUMBER(38,0),
	POPULARITY_SCORE NUMBER(38,0),
	PROCESSING_TIMESTAMP TIMESTAMP_NTZ(9),
	REVENUE_SHARE_PCT FLOAT
);