create or replace TABLE NYC_TAXI_DB.STAGE.NYC_GOLD_HOURLY_STATS (
	PICKUP_HOUR NUMBER(38,0),
	TOTAL_TRIPS NUMBER(38,0),
	AVG_TRIP_DISTANCE FLOAT,
	AVG_TRIP_DURATION FLOAT,
	AVG_FARE FLOAT,
	AVG_TIP_PERCENTAGE FLOAT,
	AVG_PASSENGERS FLOAT,
	TOTAL_REVENUE FLOAT,
	TIME_OF_DAY VARCHAR(16777216),
	PROCESSING_TIMESTAMP TIMESTAMP_NTZ(9)
);