create or replace view NYC_TAXI_DB.REPORT.VW_NYC_GOLD_PAYMENT_STATS(
	PAYMENT_TYPE,
	IS_WEEKEND,
	TOTAL_TRIPS,
	AVG_FARE,
	AVG_TIP,
	AVG_TIP_PERCENTAGE,
	TOTAL_REVENUE,
	MEDIAN_TIP_PERCENTAGE,
	PAYMENT_METHOD,
	DAY_TYPE,
	PROCESSING_TIMESTAMP
) as
SELECT
PAYMENT_TYPE,
IS_WEEKEND,
TOTAL_TRIPS,
AVG_FARE,
AVG_TIP,
AVG_TIP_PERCENTAGE,
TOTAL_REVENUE,
MEDIAN_TIP_PERCENTAGE,
PAYMENT_METHOD,
DAY_TYPE,
PROCESSING_TIMESTAMP
FROM ANALYTICS.NYC_GOLD_PAYMENT_STATS;