create or replace view NYC_TAXI_DB.REPORT.VW_NYC_GOLD_LOCATION_STATS(
	PULOCATIONID,
	TOTAL_PICKUPS,
	AVG_TRIP_DISTANCE,
	AVG_FARE,
	TOTAL_REVENUE,
	DOLOCATIONID,
	TOTAL_DROPOFFS,
	POPULARITY_SCORE,
	PROCESSING_TIMESTAMP,
	REVENUE_SHARE_PCT
) as
SELECT
PULOCATIONID,
TOTAL_PICKUPS,
AVG_TRIP_DISTANCE,
AVG_FARE,
TOTAL_REVENUE,
DOLOCATIONID,
TOTAL_DROPOFFS,
POPULARITY_SCORE,
PROCESSING_TIMESTAMP,
REVENUE_SHARE_PCT
FROM ANALYTICS.NYC_GOLD_LOCATION_STATS;