create or replace view NYC_TAXI_DB.REPORT.VW_NYC_GOLD_HOURLY_STATS(
	PICKUP_HOUR,
	TOTAL_TRIPS,
	AVG_TRIP_DISTANCE,
	AVG_TRIP_DURATION,
	AVG_FARE,
	AVG_TIP_PERCENTAGE,
	AVG_PASSENGERS,
	TOTAL_REVENUE,
	TIME_OF_DAY,
	PROCESSING_TIMESTAMP
) as
SELECT
PICKUP_HOUR,
TOTAL_TRIPS,
AVG_TRIP_DISTANCE,
AVG_TRIP_DURATION,
AVG_FARE,
AVG_TIP_PERCENTAGE,
AVG_PASSENGERS,
TOTAL_REVENUE,
TIME_OF_DAY,
PROCESSING_TIMESTAMP
FROM ANALYTICS.NYC_GOLD_HOURLY_STATS;