create or replace view NYC_TAXI_DB.REPORT.VW_NYC_GOLD_BUSINESS_STATS(
	TOTAL_TRIPS,
	TOTAL_DAYS,
	TOTAL_REVENUE,
	AVG_REVENUE_PER_TRIP,
	TOTAL_MILES,
	AVG_TRIP_DISTANCE,
	AVG_PASSENGERS,
	AVG_TIP_PERCENTAGE,
	AVG_DAILY_TRIPS,
	AVG_DAILY_REVENUE,
	REVENUE_PER_MILE,
	PROCESSING_TIMESTAMP,
	REPORT_PERIOD_START,
	REPORT_PERIOD_END
) as
SELECT
TOTAL_TRIPS,
TOTAL_DAYS,
TOTAL_REVENUE,
AVG_REVENUE_PER_TRIP,
TOTAL_MILES,
AVG_TRIP_DISTANCE,
AVG_PASSENGERS,
AVG_TIP_PERCENTAGE,
AVG_DAILY_TRIPS,
AVG_DAILY_REVENUE,
REVENUE_PER_MILE,
PROCESSING_TIMESTAMP,
REPORT_PERIOD_START,
REPORT_PERIOD_END
FROM ANALYTICS.NYC_GOLD_BUSINESS_STATS;