create or replace task NYC_TAXI_DB.ANALYTICS.TSK_MERGE_PAYMENT_STATS
	warehouse=NYC_TAXI_WH
	schedule='1 MINUTE'
	when SYSTEM$STREAM_HAS_DATA('STREAM_STAGE_PAYMENT_STATS')
	as CALL PROC_MERGE_PAYMENT_STATS();