create or replace task NYC_TAXI_DB.ANALYTICS.TSK_MERGE_DAILY_STATS
	warehouse=NYC_TAXI_WH
	schedule='1 MINUTE'
	when SYSTEM$STREAM_HAS_DATA('STREAM_STAGE_DAILY_STATS')
	as CALL PROC_MERGE_DAILY_STATS();