
CREATE OR REPLACE PROCEDURE NYC_TAXI_DB.ANALYTICS.PROC_MERGE_HOURLY_STATS()
RETURNS NUMBER(38,0)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
 MERGE INTO ANALYTICS.nyc_gold_hourly_stats t
USING stage.nyc_gold_hourly_stats s
ON t.PICKUP_HOUR = s.PICKUP_HOUR
WHEN MATCHED THEN
  UPDATE SET

t.TOTAL_TRIPS=s.TOTAL_TRIPS,
t.AVG_TRIP_DISTANCE=s.AVG_TRIP_DISTANCE,
t.AVG_TRIP_DURATION=s.AVG_TRIP_DURATION,
t.AVG_FARE=s.AVG_FARE,
t.AVG_TIP_PERCENTAGE=s.AVG_TIP_PERCENTAGE,
t.AVG_PASSENGERS=s.AVG_PASSENGERS,
t.TOTAL_REVENUE=s.TOTAL_REVENUE,
t.TIME_OF_DAY=s.TIME_OF_DAY,
t.PROCESSING_TIMESTAMP=s.PROCESSING_TIMESTAMP

WHEN NOT MATCHED THEN 
INSERT (
PICKUP_HOUR,
TOTAL_TRIPS,
AVG_TRIP_DISTANCE,
AVG_TRIP_DURATION,
AVG_FARE,
AVG_TIP_PERCENTAGE,
AVG_PASSENGERS,
TOTAL_REVENUE,
TIME_OF_DAY,
PROCESSING_TIMESTAMP
)
VALUES(
PICKUP_HOUR,
TOTAL_TRIPS,
AVG_TRIP_DISTANCE,
AVG_TRIP_DURATION,
AVG_FARE,
AVG_TIP_PERCENTAGE,
AVG_PASSENGERS,
TOTAL_REVENUE,
TIME_OF_DAY,
PROCESSING_TIMESTAMP

);

  TRUNCATE TABLE stage.nyc_gold_hourly_stats;

  RETURN 0;
END;
';