
CREATE OR REPLACE PROCEDURE NYC_TAXI_DB.ANALYTICS.PROC_MERGE_DAILY_STATS()
RETURNS NUMBER(38,0)
LANGUAGE SQL
EXECUTE AS OWNER
AS '

BEGIN
    MERGE INTO ANALYTICS.nyc_gold_daily_stats t
USING stage.nyc_gold_daily_stats s
ON t.PICKUP_DATE = s.PICKUP_DATE
WHEN MATCHED THEN
  UPDATE SET

t.TOTAL_TRIPS=s.TOTAL_TRIPS,
t.TOTAL_PASSENGERS=s.TOTAL_PASSENGERS,
t.AVG_PASSENGERS_PER_TRIP=s.AVG_PASSENGERS_PER_TRIP,
t.TOTAL_DISTANCE=s.TOTAL_DISTANCE,
t.AVG_TRIP_DISTANCE=s.AVG_TRIP_DISTANCE,
t.TOTAL_TRIP_DURATION_MINUTES=s.TOTAL_TRIP_DURATION_MINUTES,
t.AVG_TRIP_DURATION_MINUTES=s.AVG_TRIP_DURATION_MINUTES,
t.TOTAL_FARE=s.TOTAL_FARE,
t.AVG_FARE=s.AVG_FARE,
t.TOTAL_TIPS=s.TOTAL_TIPS,
t.AVG_TIP=s.AVG_TIP,
t.AVG_TIP_PERCENTAGE=s.AVG_TIP_PERCENTAGE,
t.TOTAL_REVENUE=s.TOTAL_REVENUE,
t.AVG_REVENUE_PER_TRIP=s.AVG_REVENUE_PER_TRIP,
t.AVG_SPEED_MPH=s.AVG_SPEED_MPH,
t.REVENUE_PER_MILE=s.REVENUE_PER_MILE,
t.REVENUE_PER_MINUTE=s.REVENUE_PER_MINUTE,
t.PROCESSING_TIMESTAMP=s.PROCESSING_TIMESTAMP,
t.PREV_DAY_TRIPS=s.PREV_DAY_TRIPS,
t.TRIP_GROWTH_PCT=s.TRIP_GROWTH_PCT,
t.ROLLING_7D_AVG_TRIPS=s.ROLLING_7D_AVG_TRIPS,
t.PROCESSING_TS=s.PROCESSING_TS

WHEN NOT MATCHED THEN 
INSERT (
PICKUP_DATE,
TOTAL_TRIPS,
TOTAL_PASSENGERS,
AVG_PASSENGERS_PER_TRIP,
TOTAL_DISTANCE,
AVG_TRIP_DISTANCE,
TOTAL_TRIP_DURATION_MINUTES,
AVG_TRIP_DURATION_MINUTES,
TOTAL_FARE,
AVG_FARE,
TOTAL_TIPS,
AVG_TIP,
AVG_TIP_PERCENTAGE,
TOTAL_REVENUE,
AVG_REVENUE_PER_TRIP,
AVG_SPEED_MPH,
REVENUE_PER_MILE,
REVENUE_PER_MINUTE,
PROCESSING_TIMESTAMP,
PREV_DAY_TRIPS,
TRIP_GROWTH_PCT,
ROLLING_7D_AVG_TRIPS,
PROCESSING_TS
)
VALUES(
PICKUP_DATE,
TOTAL_TRIPS,
TOTAL_PASSENGERS,
AVG_PASSENGERS_PER_TRIP,
TOTAL_DISTANCE,
AVG_TRIP_DISTANCE,
TOTAL_TRIP_DURATION_MINUTES,
AVG_TRIP_DURATION_MINUTES,
TOTAL_FARE,
AVG_FARE,
TOTAL_TIPS,
AVG_TIP,
AVG_TIP_PERCENTAGE,
TOTAL_REVENUE,
AVG_REVENUE_PER_TRIP,
AVG_SPEED_MPH,
REVENUE_PER_MILE,
REVENUE_PER_MINUTE,
PROCESSING_TIMESTAMP,
PREV_DAY_TRIPS,
TRIP_GROWTH_PCT,
ROLLING_7D_AVG_TRIPS,
PROCESSING_TS
);

  TRUNCATE TABLE stage.nyc_gold_daily_stats;

  RETURN 0;
END;
';