
CREATE OR REPLACE PROCEDURE NYC_TAXI_DB.ANALYTICS.PROC_MERGE_LOCATION_STATS()
RETURNS NUMBER(38,0)
LANGUAGE SQL
EXECUTE AS OWNER
AS '

BEGIN
  MERGE INTO ANALYTICS.nyc_gold_location_stats t
USING stage.nyc_gold_location_stats s
ON t.PULOCATIONID = s.PULOCATIONID
WHEN MATCHED THEN
  UPDATE SET


t.TOTAL_PICKUPS=s.TOTAL_PICKUPS,
t.AVG_TRIP_DISTANCE=s.AVG_TRIP_DISTANCE,
t.AVG_FARE=s.AVG_FARE,
t.TOTAL_REVENUE=s.TOTAL_REVENUE,
t.DOLOCATIONID=s.DOLOCATIONID,
t.TOTAL_DROPOFFS=s.TOTAL_DROPOFFS,
t.POPULARITY_SCORE=s.POPULARITY_SCORE,
t.PROCESSING_TIMESTAMP=s.PROCESSING_TIMESTAMP,
t.REVENUE_SHARE_PCT=s.REVENUE_SHARE_PCT

WHEN NOT MATCHED THEN 
INSERT (
PULOCATIONID,
TOTAL_PICKUPS,
AVG_TRIP_DISTANCE,
AVG_FARE,
TOTAL_REVENUE,
DOLOCATIONID,
TOTAL_DROPOFFS,
POPULARITY_SCORE,
PROCESSING_TIMESTAMP,
REVENUE_SHARE_PCT
)
VALUES(
PULOCATIONID,
TOTAL_PICKUPS,
AVG_TRIP_DISTANCE,
AVG_FARE,
TOTAL_REVENUE,
DOLOCATIONID,
TOTAL_DROPOFFS,
POPULARITY_SCORE,
PROCESSING_TIMESTAMP,
REVENUE_SHARE_PCT
);

  TRUNCATE TABLE stage.nyc_gold_location_stats;

  RETURN 0;
END;
';