

CREATE OR REPLACE PROCEDURE NYC_TAXI_DB.ANALYTICS.PROC_MERGE_BUSINESS_STATS()
RETURNS NUMBER(38,0)
LANGUAGE SQL
EXECUTE AS OWNER
AS '

BEGIN
  INSERT OVERWRITE INTO ANALYTICS.NYC_GOLD_BUSINESS_STATS (
    TOTAL_TRIPS,
TOTAL_DAYS,
TOTAL_REVENUE,
AVG_REVENUE_PER_TRIP,
TOTAL_MILES,
AVG_TRIP_DISTANCE,
AVG_PASSENGERS,
AVG_TIP_PERCENTAGE,
AVG_DAILY_TRIPS,
AVG_DAILY_REVENUE,
REVENUE_PER_MILE,
PROCESSING_TIMESTAMP,
REPORT_PERIOD_START,
REPORT_PERIOD_END
    )
    SELECT 
    TOTAL_TRIPS,
TOTAL_DAYS,
TOTAL_REVENUE,
AVG_REVENUE_PER_TRIP,
TOTAL_MILES,
AVG_TRIP_DISTANCE,
AVG_PASSENGERS,
AVG_TIP_PERCENTAGE,
AVG_DAILY_TRIPS,
AVG_DAILY_REVENUE,
REVENUE_PER_MILE,
PROCESSING_TIMESTAMP,
REPORT_PERIOD_START,
REPORT_PERIOD_END
FROM STAGE.nyc_gold_business_stats;

  TRUNCATE TABLE stage.nyc_gold_business_stats;

  RETURN 0;
END;
';