
CREATE OR REPLACE PROCEDURE NYC_TAXI_DB.ANALYTICS.PROC_MERGE_PAYMENT_STATS()
RETURNS NUMBER(38,0)
LANGUAGE SQL
EXECUTE AS OWNER
AS '

BEGIN
  MERGE INTO ANALYTICS.nyc_gold_payment_stats t
USING stage.nyc_gold_payment_stats s
ON t.PAYMENT_TYPE = s.PAYMENT_TYPE
   AND t.IS_WEEKEND = s.IS_WEEKEND
WHEN MATCHED THEN
  UPDATE SET
    t.AVG_FARE=s.AVG_FARE,
    t.MEDIAN_TIP_PERCENTAGE=s.MEDIAN_TIP_PERCENTAGE,
    t.TOTAL_REVENUE=s.TOTAL_REVENUE,
    t.AVG_TIP=s.AVG_TIP,
    t.PAYMENT_TYPE=s.PAYMENT_TYPE,
    t.PROCESSING_TIMESTAMP=s.PROCESSING_TIMESTAMP,
    t.TOTAL_TRIPS=s.TOTAL_TRIPS,
    t.AVG_TIP_PERCENTAGE=s.AVG_TIP_PERCENTAGE,
    t.PAYMENT_METHOD=s.PAYMENT_METHOD,
    t.IS_WEEKEND=s.IS_WEEKEND,
    t.DAY_TYPE=s.DAY_TYPE


WHEN NOT MATCHED THEN
  INSERT (
  PAYMENT_TYPE,
  IS_WEEKEND,
AVG_FARE	,
MEDIAN_TIP_PERCENTAGE	,
TOTAL_REVENUE	,
DAY_TYPE	,
PAYMENT_METHOD	,
TOTAL_TRIPS	,
PROCESSING_TIMESTAMP	,
AVG_TIP_PERCENTAGE	,
AVG_TIP	
  )
  VALUES (
PAYMENT_TYPE,
  IS_WEEKEND,
AVG_FARE	,
MEDIAN_TIP_PERCENTAGE	,
TOTAL_REVENUE	,
DAY_TYPE	,
PAYMENT_METHOD	,
TOTAL_TRIPS	,
PROCESSING_TIMESTAMP	,
AVG_TIP_PERCENTAGE	,
AVG_TIP
  );

  TRUNCATE TABLE stage.nyc_gold_payment_stats;

  RETURN 0;
END;
';