create or replace stream NYC_TAXI_DB.ANALYTICS.STREAM_STAGE_BUSINESS_STATS on table NYC_GOLD_BUSINESS_STATS;
create or replace stream NYC_TAXI_DB.ANALYTICS.STREAM_STAGE_DAILY_STATS on table NYC_GOLD_DAILY_STATS;
create or replace stream NYC_TAXI_DB.ANALYTICS.STREAM_STAGE_HOURLY_STATS on table NYC_GOLD_HOURLY_STATS;
create or replace stream NYC_TAXI_DB.ANALYTICS.STREAM_STAGE_LOCATION_STATS on table NYC_GOLD_LOCATION_STATS;
create or replace stream NYC_TAXI_DB.ANALYTICS.STREAM_STAGE_PAYMENT_STATS on table NYC_GOLD_PAYMENT_STATS;